#ifndef PLUGINCONTROLSYSTEMGRAPHICS_GLOBAL_H
#define PLUGINCONTROLSYSTEMGRAPHICS_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PLUGINCONTROLSYSTEMGRAPHICS_LIB
#define PLUGINCONTROLSYSTEMGRAPHICS_EXPORT Q_DECL_EXPORT
#else
#define PLUGINCONTROLSYSTEMGRAPHICS_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGINCONTROLSYSTEMGRAPHICS_GLOBAL_H
