#ifndef PLUGINELECTRICALSYSTEMGRAPHICS_GLOBAL_H
#define PLUGINELECTRICALSYSTEMGRAPHICS_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PLUGINELECTRICALSYSTEMGRAPHICS_LIB
#define PLUGINELECTRICALSYSTEMGRAPHICS_EXPORT Q_DECL_EXPORT
#else
#define PLUGINELECTRICALSYSTEMGRAPHICS_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGINELECTRICALSYSTEMGRAPHICS_GLOBAL_H
