#ifndef PLUGINSTATEMACHINEGRAPHICS_GLOBAL_H
#define PLUGINSTATEMACHINEGRAPHICS_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PLUGINSTATEMACHINEGRAPHICS_LIB
#define PLUGINSTATEMACHINEGRAPHICS_EXPORT Q_DECL_EXPORT
#else
#define PLUGINSTATEMACHINEGRAPHICS_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGINSTATEMACHINEGRAPHICS_GLOBAL_H
