# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: device.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64\x65vice.proto\x12\x0e\x64\x65vice_service\",\n\x15\x44\x65viceNameListRequest\x12\x13\n\x0b\x64\x65vice_name\x18\x01 \x01(\t\".\n\x16\x44\x65viceNameListResponse\x12\x14\n\x0c\x64\x65vice_names\x18\x01 \x03(\t\"\x7f\n\x10\x44\x65viceInfoDetail\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x15\n\rserver_status\x18\x04 \x01(\x08\x12\x17\n\x0fsimulate_status\x18\x05 \x01(\x08\x12\x13\n\x0bplan_status\x18\x06 \x01(\x08\"(\n\x11\x44\x65viceInfoRequest\x12\x13\n\x0b\x64\x65vice_name\x18\x01 \x01(\t\"D\n\x12\x44\x65viceInfoResponse\x12.\n\x04info\x18\x01 \x01(\x0b\x32 .device_service.DeviceInfoDetail\",\n\x15\x44\x65viceSlaveCntRequest\x12\x13\n\x0b\x64\x65vice_name\x18\x01 \x01(\t\"+\n\x16\x44\x65viceSlaveCntResponse\x12\x11\n\tslave_cnt\x18\x01 \x01(\x05\"X\n\x1b\x44\x65viceTableBySlaveIdRequest\x12\x13\n\x0b\x64\x65vice_name\x18\x01 \x01(\t\x12\x10\n\x08slave_id\x18\x02 \x01(\x05\x12\x12\n\npoint_name\x18\x03 \x01(\t\"\x1d\n\x0e\x44\x65viceTableRow\x12\x0b\n\x03row\x18\x01 \x03(\t\"\x85\x01\n\x1c\x44\x65viceTableBySlaveIdResponse\x12\x31\n\thead_data\x18\x01 \x01(\x0b\x32\x1e.device_service.DeviceTableRow\x12\x32\n\ntable_data\x18\x02 \x03(\x0b\x32\x1e.device_service.DeviceTableRow2\xaf\x03\n\rDeviceService\x12\x66\n\x13GetDeviceStringList\x12%.device_service.DeviceNameListRequest\x1a&.device_service.DeviceNameListResponse\"\x00\x12\x64\n\x11GetDeviceSlaveCnt\x12%.device_service.DeviceSlaveCntRequest\x1a&.device_service.DeviceSlaveCntResponse\"\x00\x12X\n\rGetDeviceInfo\x12!.device_service.DeviceInfoRequest\x1a\".device_service.DeviceInfoResponse\"\x00\x12v\n\x17GetDeviceTableBySlaveId\x12+.device_service.DeviceTableBySlaveIdRequest\x1a,.device_service.DeviceTableBySlaveIdResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'device_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DEVICENAMELISTREQUEST']._serialized_start=32
  _globals['_DEVICENAMELISTREQUEST']._serialized_end=76
  _globals['_DEVICENAMELISTRESPONSE']._serialized_start=78
  _globals['_DEVICENAMELISTRESPONSE']._serialized_end=124
  _globals['_DEVICEINFODETAIL']._serialized_start=126
  _globals['_DEVICEINFODETAIL']._serialized_end=253
  _globals['_DEVICEINFOREQUEST']._serialized_start=255
  _globals['_DEVICEINFOREQUEST']._serialized_end=295
  _globals['_DEVICEINFORESPONSE']._serialized_start=297
  _globals['_DEVICEINFORESPONSE']._serialized_end=365
  _globals['_DEVICESLAVECNTREQUEST']._serialized_start=367
  _globals['_DEVICESLAVECNTREQUEST']._serialized_end=411
  _globals['_DEVICESLAVECNTRESPONSE']._serialized_start=413
  _globals['_DEVICESLAVECNTRESPONSE']._serialized_end=456
  _globals['_DEVICETABLEBYSLAVEIDREQUEST']._serialized_start=458
  _globals['_DEVICETABLEBYSLAVEIDREQUEST']._serialized_end=546
  _globals['_DEVICETABLEROW']._serialized_start=548
  _globals['_DEVICETABLEROW']._serialized_end=577
  _globals['_DEVICETABLEBYSLAVEIDRESPONSE']._serialized_start=580
  _globals['_DEVICETABLEBYSLAVEIDRESPONSE']._serialized_end=713
  _globals['_DEVICESERVICE']._serialized_start=716
  _globals['_DEVICESERVICE']._serialized_end=1147
# @@protoc_insertion_point(module_scope)
